[package]
org = "digitalpaymentshub"
name = "digital.payments.payment_hub"
version = "0.9.0"
distribution = "2201.10.0"
authors = ["Ballerina"]
visibility="private"

[[dependency]]
org = "digitalpaymentshub"
name = "driver.utils"
version = "0.0.15"
repository = "local"

