[package]
org = "digitalpaymentshub"
name = "drivers.sampledriver"
version = "0.0.2"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "digitalpaymentshub"
name = "drivers.utils"
version = "0.0.34"
repository = "local"

[[dependency]]
org = "digitalpaymentshub"
name = "payments_hub"
repository = "local"
version = "0.0.16"
