[package]
org = "digitalpaymentshub"
name = "drivers.xpay"
version = "0.0.1"
distribution = "2201.10.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "digitalpaymentshub"
name = "drivers.utils"
version = "0.0.34"
repository = "local"

[[dependency]]
org = "digitalpaymentshub"
name = "payments_hub"
repository = "local"
version = "0.0.16"

[[dependency]]
org = "ballerinax"
name = "financial.iso8583"
version = "0.1.6"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "financial.iso20022"
version = "0.0.4"
repository = "local"
