[driver]
name = "xpay"
code = "LK"

[driver.inbound]
transport = "tcp"
host = "localhost"
port = 8085

# url of the country switch
[driver.outbound]
transport = "tcp"
host = "localhost"
port = 8200

# hub facing api of the driver
[driver.driver_api]
host = "localhost"
port = 9091
gateway_url = "http://localhost:9091"

[payments_hub]
base_url = "http://localhost:9100"

[ballerina.log]
level = "DEBUG"
