[package]
org = "digitalpaymentshub"
name = "digital.payments.hub.lankapay"
version = "0.0.1"
distribution = "2201.9.2"
authors = ["Ballerina"]
visibility="private"

[[dependency]]
org = "ballerinax"
name = "financial.iso8583"
version = "0.1.1"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "financial.iso20022"
version = "0.0.4"
repository = "local"

[[dependency]]
org = "digitalpaymentshub"
name = "digital.payments.hub.driver_manager"
version = "0.0.2"
repository = "local"

[[dependency]]
org = "digitalpaymentshub"
name = "digital.payments.hub.paynet"
version = "0.0.3"
repository = "local"
